name = "EfinaModPack-Core"
author = "Efina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "157b9884466c0ab91a401f39fb21822d010bacdc9ea232d41513367b35137f80"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
