name = "EfinaModPack-Core"
author = "Efina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff56511c9fc12abbd9714a9d11999fc871c1569a2a2151bde33d40ceae01b872"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.4"
