name = "EfinaModPack-Lite"
author = "Efina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ecf417b4687790e7b93c10bdc8a97a094862f14100978002811a90bc955d280"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
