name = "EfinaModPack-Lite"
author = "Efina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75832d8c19a11e23cb011c677d2a88c763f9ec1eef9b7c5fe391233bed34c830"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
