name = "EfinaModPack-Lite"
author = "Efina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1797a2222d15b356adf238c40ba5c0c78f62b62a4e0647cbeab4c734e061657b"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
