name = "EfinaModPack-Lite"
author = "Efina"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0eda15b0682e40ee338b42db57b81a4f5a3fccbbc18f6635ec73ba1db7e45b2"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.6"
