name: AutoPack

on:
  push:
    branches:
    - main
    # paths:
    # - assets/**
    # - pack.mcmeta
  workflow_dispatch: {}

jobs:
  ModPack-PerRealease:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2.0.0

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'

      - name: Install Packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
          packwiz --help

      - name: Git Version Info
        id: version
        run: |
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: ModPack Export
        run: |
          cd LitePack/
          packwiz mr export
          mv *.mrpack ..

      - name: Make Checksum
        id: checksum
        run: |
          echo "::set-output name=sum-01::$(sha256sum EfinaModPack-Lite-[0-9].[0-9].[0-9].mrpack)"

      - name: Push Pack to Per-Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.mrpack"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: Efina 模組包-最新版 (git ${{ steps.version.outputs.sha_short }})
          body: |
            ## ✅ Checksum
            ```
            ${{ steps.checksum.outputs.sum-01 }}
            ```
