name: AutoPack

on:
  push:
    branches:
    - main
    paths:
    - LitePack/**
  workflow_dispatch: {}

jobs:
  ModPack-PerRealease:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2.0.0

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'

      - name: Install Packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
          packwiz --help

      - name: Set Git Version Info
        id: version
        run: |
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: ModPack Export (Modrinth)
        run: |
          cp LICENSE LitePack/
          cd LitePack/
          packwiz mr export
          mv *.mrpack ..

      - name: ModPack Export (CurseForge)
        run: |
          cd LitePack/
          packwiz cf export
          cd ..
          cp -r LitePack LitePack-CF
          cd LitePack-CF
          rm -r mods
          mkdir Temp
          cd Temp
          mv ../EfinaModPack-Lite-[0-9].[0-9].[0-9].zip .
          unzip EfinaModPack-Lite-[0-9].[0-9].[0-9].zip
          cd ..
          cp -r Temp/overrides/mods .
          rm -r Temp
          packwiz cf detect
          packwiz cf export
          mv *.zip ..

      - name: Make Checksum
        id: checksum
        run: |
          echo "::set-output name=sum-01::$(sha256sum EfinaModPack-Lite-[0-9].[0-9].[0-9].mrpack)"
          echo "::set-output name=sum-02::$(sha256sum EfinaModPack-Lite-[0-9].[0-9].[0-9].zip)"

      - name: Push Pack to Per-Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.mrpack,*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: Efina ModPack-Latest (git ${{ steps.version.outputs.sha_short }})
          body: |
            ## ✅ Checksum
            ```
            ${{ steps.checksum.outputs.sum-01 }}
            ${{ steps.checksum.outputs.sum-02 }}
            ```
